# gen_manifest.cmake
# 引数: SRC_DIR (samples ディレクトリ), OUT_FILE (manifest.json の出力先)
file(GLOB files RELATIVE "${SRC_DIR}" "${SRC_DIR}/*.txt")
list(SORT files)
set(json "[\n")
list(LENGTH files n)
set(i 0)
foreach(f ${files})
    math(EXPR i "${i}+1")
    if(i LESS n)
        string(APPEND json "  \"${f}\",\n")
    else()
        string(APPEND json "  \"${f}\"\n")
    endif()
endforeach()
string(APPEND json "]\n")
file(WRITE "${OUT_FILE}" "${json}")
